# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Currency

# Model Form Field configuration
form: $/zohan/currency/models/currency/fields.yaml

# Model Class name
modelClass: Zohan\Currency\Models\Currency

# Default redirect location
defaultRedirect: zohan/currency/currencies

# Create page
create:
    title: backend::lang.form.create_title
    redirect: zohan/currency/currencies/update/:id
    redirectClose: zohan/currency/currencies

# Update page
update:
    title: backend::lang.form.update_title
    redirect: zohan/currency/currencies
    redirectClose: zohan/currency/currencies

# Preview page
preview:
    title: backend::lang.form.preview_title
